### ISSUE TITLE
vue 模版, 无法部署到阿里云, 安装 fc-adapter 和 fc-plugin, 但 cli程序 却 非要向 腾讯云部署..

### ISSUE THREAD

**Issue by raiscui** [cellbang/malagu#117]
<img width="751" alt="image" src="https://user-images.githubusercontent.com/857943/153738143-903b26b8-5f7d-48eb-8edf-87a78a44487b.png">

==========================================
都是 malagu init vue-app ,  没动过什么, 只是添加了 fc-adapter 和 fc-plugin.

这是 package

```
{
  "name": "vue-app",
  "keywords": [
    "malagu-component"
  ],
  "version": "0.0.0",
  "license": "MIT",
  "files": [
    "lib",
    "src"
  ],
  "dependencies": {
    "@malagu/cli-service": "^2.10.2",
    "@malagu/core": "latest",
    "@malagu/fc-adapter": "^2.10.2",
    "@malagu/rpc": "latest",
    "@malagu/serve-static": "latest",
    "@malagu/vue": "latest",
    "vue": "^3.0.11",
    "vue-router": "^4.0.8"
  },
  "devDependencies": {
    "@malagu/cli": "latest",
    "@malagu/fc-plugin": "^2.10.2"
  },
  "scripts": {
    "clean": "rimraf lib dist .malagu",
    "build": "malagu build",
    "start": "malagu serve",
    "deploy": "malagu deploy -m test",
    "deploy:test": "malagu deploy -m test",
    "deploy:pre": "malagu deploy -m pre",
    "deploy:prod": "malagu deploy -m prod"
  }
}

```
==========
这是命令行

```

cuiluming@RaisdeAir vue-app % npm run clean

> vue-app@0.0.0 clean /Users/cuiluming/Nextcloud/dev_chaoway/js/vue-app
> rimraf lib dist .malagu

cuiluming@RaisdeAir vue-app % yarn run deploy
yarn run v1.22.17
warning ../package.json: No license field
$ malagu deploy -m test

                   ___
 /'\_/`\          /\_ \
/\      \     __  \//\ \      __       __   __  __
\ \ \__\ \  /'__`\  \ \ \   /'__`\   /'_ `\/\ \/\ \
 \ \ \_/\ \/\ \L\.\_ \_\ \_/\ \L\.\_/\ \L\ \ \ \_\ \
  \ \_\\ \_\ \__/.\_\/\____\ \__/.\_\ \____ \ \____/
   \/_/ \/_/\/__/\/_/\/____/\/__/\/_/\/___L\ \/___/
                                       /\____/
                   @malagu/cli@2.10.2  \_/__/

╭──────────────────────────────────────────────────╮
│      Serverless First Development Framework      │
│                 Runtime<malagu>                  │
╰──────────────────────────────────────────────────╯

🏔   malagu stage - test
🏷   malagu mode - remote
🏷   malagu mode - test
🏷   malagu mode - auto
🏷   malagu mode - scf-adapter
🏷   malagu mode - scf
🎯  malagu target - backend
🎯  malagu target - frontend
🧱  malagu component - @malagu/core@2.10.2
🧱  malagu component - @malagu/cloud@2.10.2
🧱  malagu component - @malagu/schedule@2.10.2
🧱  malagu component - @malagu/faas-adapter@2.10.2
🧱  malagu component - @malagu/web@2.10.2
🧱  malagu component - @malagu/scf-adapter@2.10.2
🧱  malagu component - @malagu/cli-service@^2.10.2
🧱  malagu component - @malagu/fc-adapter@^2.10.2
🧱  malagu component - @malagu/rpc@latest
🧱  malagu component - @malagu/serve-static@latest
🧱  malagu component - @malagu/vue@latest
🧱  malagu component - @malagu/cloud-plugin@2.10.2
🧱  malagu component - @malagu/code-loader-plugin@2.10.2
🧱  malagu component - @malagu/scf-plugin@2.10.2
🧱  malagu component - @malagu/fc-plugin@^2.10.2
🧱  malagu component - vue-app@0.0.0
backend build [====================] 98% (3.3 seconds) DONE  Compiled successfully in 3316ms                                                          11:55:27

 I  The backend code output to /Users/cuiluming/Nextcloud/dev_chaoway/js/vue-app/.malagu/dist/backend 🎉

Build completed in 3.533s

frontend build [==================  ] 92% (6.4 seconds) DONE  Compiled successfully in 6387ms                                                          11:55:34

 I  The frontend code output to /Users/cuiluming/Nextcloud/dev_chaoway/js/vue-app/.malagu/dist/frontend 🎉

frontend build [====================] 99% (6.5 seconds) DONE  Compiled successfully in 6387ms                                                          11:55:34

 I  The frontend code output to /Users/cuiluming/Nextcloud/dev_chaoway/js/vue-app/.malagu/dist/frontend 🎉

 DONE  Compiled successfully in 6387ms                                                          11:55:34

 I  The frontend code output to /Users/cuiluming/Nextcloud/dev_chaoway/js/vue-app/.malagu/dist/frontend 🎉

frontend build [====================] 99% (6.6 seconds) DONE  Compiled successfully in 6387ms                                                          11:55:34

 I  The frontend code output to /Users/cuiluming/Nextcloud/dev_chaoway/js/vue-app/.malagu/dist/frontend 🎉

Build completed in 6.64s


Deploying vue-app to the cn-hangzhou region of alibaba cloud...
- Profile: 
    - AccountId: 1236284087205882
    - Region: cn-hangzhou
- SCF:
TencentCloudSDKHttpException [Error]: The SecretId is not found, please ensure that your SecretId is correct.
    at Client.parseResponse (/Users/cuiluming/.malagu/runtimes/2.10.2/default/node_modules/tencentcloud-sdk-nodejs/tencentcloud/common/abstract_client.js:134:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at Client.request (/Users/cuiluming/.malagu/runtimes/2.10.2/default/node_modules/tencentcloud-sdk-nodejs/tencentcloud/common/abstract_client.js:65:28)
    at getNamespace (/Users/cuiluming/.malagu/runtimes/2.10.2/default/node_modules/@malagu/scf-plugin/src/hooks/utils.ts:209:36)
    at createOrUpdateNamespace (/Users/cuiluming/.malagu/runtimes/2.10.2/default/node_modules/@malagu/scf-plugin/src/hooks/deploy.ts:130:27)
    at Object.exports.default (/Users/cuiluming/.malagu/runtimes/2.10.2/default/node_modules/@malagu/scf-plugin/src/hooks/deploy.ts:40:5)
    at HookExecutor.doRequire (/Users/cuiluming/Nextcloud/dev_chaoway/js/vue-app/node_modules/@malagu/cli-common/src/hook/hook-executor.ts:70:24)
    at HookExecutor.doExecuteHooks (/Users/cuiluming/Nextcloud/dev_chaoway/js/vue-app/node_modules/@malagu/cli-common/src/hook/hook-executor.ts:111:33)
    at exports.default (/Users/cuiluming/Nextcloud/dev_chaoway/js/vue-app/node_modules/@malagu/cli-service/src/deploy/deploy.ts:33:9) {
  requestId: '4258a483-31f4-47d1-ac1b-d381eead25a8',
  code: 'AuthFailure.SecretIdNotFound'
}
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by JarynChen** [comment]
部署的时候加上-m fc，或者在yml中添加 mode: fc 即可

**Comment by JarynChen** [comment]
具体原因: malagu 2.x中提供了运行时机制，默认运行时会部署到腾讯云scf，会自动安装所需要的依赖，如果指定mode为fc，则会启用fc模式，会自动安装部署到阿里云的所需依赖，简化部署

**Comment by raiscui** [comment]
感谢 ,  部署成功,

**Comment by raiscui** [comment]
图片路径在最终html上 不对,   去掉 “../” ,  直接 src="62a066930b811a8c184e.png"  显示正确.


<img width="1010" alt="image" src="https://user-images.githubusercontent.com/857943/153739166-d061ecd6-b03f-457c-87a2-8a0a8113764b.png">

<img width="285" alt="image" src="https://user-images.githubusercontent.com/857943/153739193-d4161f11-1e06-4f9d-bc9c-9228458b54e6.png">

**Comment by JarynChen** [comment]
> 
> 
> 图片路径在最终html上 不对,   去掉 “../” ,  直接 src="62a066930b811a8c184e.png"  显示正确.
> 
> 
> <img width="1010" alt="image" src="https://user-images.githubusercontent.com/857943/153739166-d061ecd6-b03f-457c-87a2-8a0a8113764b.png">
> 
> <img width="285" alt="image" src="https://user-images.githubusercontent.com/857943/153739193-d4161f11-1e06-4f9d-bc9c-9228458b54e6.png">
> 

收到，我们排查下，感谢

**Comment by JarynChen** [comment]
请更新至2.11.1版本，此问题已修复，感谢！🙏
