### ISSUE TITLE
没有Monorepo这个模板了，文档需要改下。

### ISSUE THREAD

**Issue by meiziRain** [cellbang/malagu#146]
/'\_/`\          /\_ \
/\      \     __  \//\ \      __       __   __  __
\ \ \__\ \  /'__`\  \ \ \   /'__`\   /'_ `\/\ \/\ \
 \ \ \_/\ \/\ \L\.\_ \_\ \_/\ \L\.\_/\ \L\ \ \ \_\ \
  \ \_\\ \_\ \__/.\_\/\____\ \__/.\_\ \____ \ \____/
   \/_/ \/_/\/__/\/_/\/____/\/__/\/_/\/___L\ \/___/
                                       /\____/
                   @malagu/cli@2.23.1  \_/__/

╭──────────────────────────────────────────────────╮
│      Serverless First Development Framework      │
│                 Runtime<malagu>                  │
╰──────────────────────────────────────────────────╯

AssertionError [ERR_ASSERTION]: "monorepo" template not found
    at InitManager.selectTemplate (D:\workspace\vue-app\node_modules\@malagu\cli\src\init\init-manager.ts:117:19)
    at InitManager.output (D:\workspace\vue-app\node_modules\@malagu\cli\src\init\init-manager.ts:42:20)
    at Object.exports.default (D:\workspace\vue-app\node_modules\@malagu\cli\src\init\init.ts:6:27)
    at Command.<anonymous> (D:\workspace\vue-app\node_modules\@malagu\cli\src\malagu.ts:58:43)
    at Command.listener [as _actionHandler] (D:\workspace\vue-app\node_modules\commander\lib\command.js:488:17)
    at D:\workspace\vue-app\node_modules\commander\lib\command.js:1227:65
    at Command._chainOrCall (D:\workspace\vue-app\node_modules\commander\lib\command.js:1144:12)
    at Command._parseCommand (D:\workspace\vue-app\node_modules\commander\lib\command.js:1227:27)
    at Command._dispatchSubcommand (D:\workspace\vue-app\node_modules\commander\lib\command.js:1050:25)
    at Command._parseCommand (D:\workspace\vue-app\node_modules\commander\lib\command.js:1193:19) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}

**Comment by JarynChen** [comment]
感谢反馈，我们更新一下，推荐使用微服务模板
