### ISSUE TITLE
检查sample-app 项目使用 pnpm

### ISSUE THREAD

**Issue by bingtsingw** [cellbang/malagu#169]

**Comment by bingtsingw** [comment]
```
malagu init -p pnpm
# select sample-app
pnpm start
```

编译没有报错, 运行会报错, 错误位置在 `hello.view.tsx`
```
const welcomeServer = RpcUtil.get<WelcomeServer>(WelcomeServer);
```

```
Error: No matching bindings found for serviceIdentifier: Symbol(RestOperations)
    at _validateActiveBindingCount (planner.js:59:1)
    at _getActiveBindings (planner.js:45:1)
    at _createSubRequests (planner.js:86:1)
    at planner.js:110:1
    at Array.forEach (<anonymous>)
    at planner.js:109:1
    at Array.forEach (<anonymous>)
    at _createSubRequests (planner.js:89:1)
    at plan (planner.js:131:1)
    at container.js:598:31
```
