### ISSUE TITLE
First time use 'malagu serve' but with errors

### ISSUE THREAD

**Issue by Cornicione** [cellbang/malagu#206]
PS C:\Users\Beelink\Application\malagu-project> malagu serve

                   ___
 /'\_/`\          /\_ \
/\      \     __  \//\ \      __       __   __  __
\ \ \__\ \  /'__`\  \ \ \   /'__`\   /'_ `\/\ \/\ \
 \ \ \_/\ \/\ \L\.\_ \_\ \_/\ \L\.\_/\ \L\ \ \ \_\ \
  \ \_\\ \_\ \__/.\_\/\____\ \__/.\_\ \____ \ \____/
   \/_/ \/_/\/__/\/_/\/____/\/__/\/_/\/___L\ \/___/
                                       /\____/
                   @malagu/cli@2.55.4  \_/__/

╭──────────────────────────────────────────────────╮
│      Serverless First Development Framework      │
│                 Runtime<malagu>                  │
╰──────────────────────────────────────────────────╯

× Installing @malagu/cli-service@2.55.4 in default runtime...
Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at C:\Users\Beelink\AppData\Roaming\npm\node_modules\@malagu\cli\node_modules\@malagu\cli-common\lib\packager\utils.js:27:53
    at new Promise (<anonymous>)
    at spawnProcess (C:\Users\Beelink\AppData\Roaming\npm\node_modules\@malagu\cli\node_modules\@malagu\cli-common\lib\packager\utils.js:21:12)
    at NPM.add (C:\Users\Beelink\AppData\Roaming\npm\node_modules\@malagu\cli\node_modules\@malagu\cli-common\lib\packager\npm.js:107:41)
    at C:\Users\Beelink\AppData\Roaming\npm\node_modules\@malagu\cli\node_modules\@malagu\cli-common\lib\context\context-protocol.js:30:36
    at Object.start (C:\Users\Beelink\AppData\Roaming\npm\node_modules\@malagu\cli\node_modules\@malagu\cli-common\lib\utils\spinner-util.js:17:31)
    at installComponent (C:\Users\Beelink\AppData\Roaming\npm\node_modules\@malagu\cli\node_modules\@malagu\cli-common\lib\context\context-protocol.js:29:50)
    at installComponents (C:\Users\Beelink\AppData\Roaming\npm\node_modules\@malagu\cli\node_modules\@malagu\cli-common\lib\context\context-protocol.js:58:27) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}
PS C:\Users\Beelink\Application\malagu-project>

**Comment by Cornicione** [comment]
I am new to malagu, and what i did was just follow the Tutorial. I use win11 and use nodejs v20.12.2(LTS) x64

**Comment by muxiangqiu** [comment]
使用最新版本再试试看
