### ISSUE TITLE
微服务更多的文档和示例代码

### ISSUE THREAD

**Issue by universeroc** [cellbang/malagu#67]
https://www.yuque.com/cellbang/malagu/wtiy6s

上面文档，在端点配置，以及完整使用方面无法正常跑通，希望提供更详细的 demo 可以完整运行

**Comment by universeroc** [comment]
> 你好，无法正常跑通有相关的错误的截图吗，希望可以进一步排查。另外在使用cli创建项目的时候，可以选择micro service模板，参考模板快速上手微服务

嗯，就是采用的模板进行的创建

```
starting GET /api/WelcomeServer with traceId[900b63f2-bca2-4f2b-9297-fd0763a2f148] 
ending GET /api/WelcomeServer with traceId[900b63f2-bca2-4f2b-9297-fd0763a2f148], cost 5ms
NotFoundError: Not found a suitable handler adapter: /api/WelcomeServer
    at HandlerMappingImpl.handle (webpack-internal:///./node_modules/@malagu/web/lib/node/handler/handler-mapping.js:47:15)  
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at SessionMiddleware.handle (webpack-internal:///./node_modules/@malagu/web/lib/node/session/session-middleware.js:24:13)
    at CookiesMiddleware.handle (webpack-internal:///./node_modules/@malagu/web/lib/node/cookies/cookies-middleware.js:26:9) 
    at HttpMiddleware.handle (webpack-internal:///./node_modules/@malagu/web/lib/node/http/http-middleware.js:19:9)
    at ChannelMiddleware.handle (webpack-internal:///./node_modules/@malagu/rpc/lib/node/channel/channel-middleware.js:29:9) 
    at TraceMiddleware.handle (webpack-internal:///./node_modules/@malagu/web/lib/node/trace/trace-middleware.js:31:13)      
    at DispatcherImpl.dispatch (webpack-internal:///./node_modules/@malagu/web/lib/node/dispatcher/dispatcher.js:24:13) {    
  statusCode: 404
}
```

**Comment by muxiangqiu** [comment]
@universeroc 微服务是否对外直接访问有你的业务决定，backend-app 只是一个示例项目，用于演示如何在后端（bff）中，调用微服务。
