### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'intercept')

### ISSUE THREAD

**Issue by pbpoon** [cellbang/malagu#73]
当malagu init项目后，运行malagu serve就出现这个情况
frontend build [                    ] 0% (0.0 seconds)TypeError: Cannot read properties of undefined (reading 'intercept')
    at /Users/vincent_pun/Desktop/test/sample-app/node_modules/webpack/lib/ProgressPlugin.js:242:30
    at Array.forEach (<anonymous>)
    at /Users/vincent_pun/Desktop/test/sample-app/node_modules/webpack/lib/ProgressPlugin.js:239:24
    at Hook.eval (eval at create (/Users/vincent_pun/Desktop/test/sample-app/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:104:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/vincent_pun/Desktop/test/sample-app/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/vincent_pun/Desktop/test/sample-app/node_modules/@malagu/cli-service/node_modules/webpack/lib/Compiler.js:1055:26)
    at /Users/vincent_pun/Desktop/test/sample-app/node_modules/@malagu/cli-service/node_modules/webpack/lib/Compiler.js:1099:29
    at Hook.eval [as callAsync] (eval at create (/Users/vincent_pun/Desktop/test/sample-app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/vincent_pun/Desktop/test/sample-app/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/vincent_pun/Desktop/test/sample-app/node_modules/@malagu/cli-service/node_modules/webpack/lib/Compiler.js:1094:28)
λ ~/Desktop/test/sample-app/ npm install -g @malagu/cli

**Comment by pbpoon** [comment]
请问这个怎么解决，我在nvm的试过node14及node16的环境都是这样的情况

**Comment by muxiangqiu** [comment]
我这边尝试复现一下

**Comment by muxiangqiu** [comment]
我这边试了一下 malagu 是 v2.1.1，node 是 v14.18.1，在 macos 上没有问题

**Comment by muxiangqiu** [comment]
windows 10;
node 12/16；
malagu v2.1.1 
也没有发现问题，你可以确认一下你的 malagu 版本，尝试升级一下看看

**Comment by pbpoon** [comment]
> 

谢谢你的帮忙，我这边malagu：2.1.1， node 16.13.1， macOS 12.0.1 M1，还是未能解决问题

**Comment by muxiangqiu** [comment]
malagu：2.1.1， node 16.13.1 在非 M1 的 macos 上运行正常，目前找不到 M1 的电脑，你看看能否帮我们在非 M1 的电脑试试

**Comment by pbpoon** [comment]
问题已经解决，在google上搜索相关问题，发现是包内的webpack的版本问题，npm i webpack@5 后问题已经解决

**Comment by muxiangqiu** [comment]
你是自己安装的包中引入了低版本的 webpack 吗？

**Comment by pbpoon** [comment]
> 你是自己安装的包中引入了低版本的 webpack 吗？

没有，我是按教程来的，
npm i -g @malagu/cli
malagu init
这样一步一步来的

**Comment by muxiangqiu** [comment]
你是用 npm 来安装依赖的吗？我这边用的是 yarn，我等会试试 npm 安装看看

**Comment by pbpoon** [comment]
> 你是用 npm 来安装依赖的吗？我这边用的是 yarn，我等会试试 npm 安装看看

是用npm

**Comment by muxiangqiu** [comment]
已经解决
